### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by timblack1** [hoodiehq/hoodie-server#280]
When I refresh the page of my Hoodie app in my browser, the memory usage of hoodie-server/bin/start increases regularly by somewhere between 0.2 to 1.0 MB.  It also increases by a small amount when Hoodie polls /_api/ and the global share's _changes feed every 30 seconds.  Is this a memory leak?

I'm running Hoodie "Version: 0.4.9 (node v0.10.28, npm 1.4.9, platform: linux)"

**Comment by inator** [comment]
@janl & @boennemann - Were you ever able to track this down?  The newest version of Hoodie seems to still exhibit it (server 2.0.0).  We've been forced to downgrade several instances back to server version 1.2.4 to keep things stable, but that comes at the cost of not getting the latest features.

**Comment by janl** [comment]
@inator no updates yet, but I’ll bump it up on my list of things to look at.

**Comment by janl** [comment]
@timblack1 do your processes ever run out of memory? Some fluctuation in memory is expected as the garbage collector kicks in.

@inator how long does it take for your process to go OOM?

**Comment by janl** [comment]
That said, looking a a run with `heapdump` and periodic SIGUSR2 (which triggers GC), I see a slight increase in the baseline memory used.

**Comment by janl** [comment]
TODO: We should check if this could be it: https://github.com/hapijs/hapi/issues/1634 — unfortunately, this means porting up to hapi 8.1, but that’s something we wanted to do anyway.

I got some info out of the heap profiler that might point to this, in fact, but I’m not entirely sure I’m doing this right. In addition, I can’t seem to get to see what @timblack1 has shown, but that could just be the code evolving since then.

![screen shot 2015-01-08 at 23 32 09](https://cloud.githubusercontent.com/assets/11321/5672195/c147005e-978e-11e4-87c6-94fe1a5feb19.png)

**Comment by inator** [comment]
It depends on the activity.  I have observed that when a backend is idle and just receiving the customary periodic changes requests form a single client, it can take 24-48 hours.

**Comment by inator** [comment]
@janl - btw I agree it could be HAPI related since an app that isn't receiving regular requests doesn't crash as far as I can tell.  I have many running that are receiving zero traffic and they have been up for weeks.  It the apps that have an active client (polling for changes) that eventually crash.

**Comment by timblack1** [comment]
@janl, no, my processes don't run out of memory, but that might be because I never let them run long enough to do so.  I haven't deployed any Hoodie apps yet; they are still in development.

Currently I'm on Hoodie "Version: 0.6.3 (node v0.10.29, npm 2.1.8, platform: linux)," and it appears to me that the memory leak remains.

**Comment by inator** [comment]
@janl : Sorry to report we're still seeing this with server version 3.1.1.  I've provided the attached chart, which shows roughly double the memory use (red line) over around ~17 hours with only 1 connected hoodie client (default Hoodie WWW front end).

![hoodie mem leak](https://cloud.githubusercontent.com/assets/777300/7670821/15d79068-fc69-11e4-92a5-a941d52a07fc.png)

What can I do to help?

**Comment by janl** [comment]
@inator what we’d need to find out is which type of request makes the memory leak and then find the leak :) — It’ll be a lot of testing and instrumenting and reading source code carefully.

**Comment by janl** [comment]
@inator wanna give this branch a try? https://github.com/hoodiehq/hoodie-server/pull/346

**Comment by boennemann** [comment]
The code that was probably causing this is pretty much 100% gone with the hoodie-server rewrite. I'm closing this for now, and we can reopen as soon as we're having the same problem again.

**Comment by timblack1** [comment]
:+1:

**Comment by timblack1** [comment]
I'm going to delete the stuff I uploaded to my server above, then.  Maybe it will remain on the Internet Archive if anyone needs it.
