### ISSUE TITLE
[next] prompt user for admin password on first run

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-server#380]
This works in master, the experience is very nice, we should keep it.

It’s still great that you can now pass the admin password via command line flags, but for a first-run experience, the readline version is more friendly.

**Comment by boennemann** [comment]
We removed it for now (with the intent to reintroduce it), because we tried to clearly separate out responsibilities of the server and cli/start script. I think it should belong here: https://github.com/hoodiehq/hoodie/blob/master/bin/start.js, but there isn't all the information available that's required to know whether the admin-password is needed at this point.

**Comment by boennemann** [comment]
A password for the PouchDB is now no longer required, because it's running in the same process.
So this issue does no longer apply unless https://github.com/hoodiehq/hoodie-server/issues/384 lands.
