### ISSUE TITLE
[new Hoodie] connection status route

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#420]
Of the [hoodie.connectionStatus](https://github.com/hoodiehq/hoodie-client-connection-status) API, we need a route that we can ping.

I'd suggest `HEAD /hoodie/connection-status/api`

I don't think this needs any other route for now, and if we extend it in future, I don't think we would need a breaking change, only add new routes

**Comment by boennemann** [comment]
Is there any reason why `HEAD /hoodie` wouldn't work for this?

**Comment by gr2m** [comment]
`HEAD /hoodie` would work, but we might use `/hoodie` for something else in future, like a simple html page showing Hoodie version etc. `HEAD /hoodie/connection-status/api` would follow the conventions of the other routes for account, store & task, and future plugins

**Comment by boennemann** [comment]
`/hoodie` is the CouchDB right now, so that's already taken. If we would want to serve html there, we could still do it based on the Accept Header (same goes for the other components btw). So for now, without any other requirements, `HEAD /hoodie` would be fine. As there is no server side implementation needed and no module I don't see which convention we are following by adding a route to hoodie-server for this.

**Comment by gr2m** [comment]
> /hoodie is the CouchDB right now, so that's already taken

I would like to change that before we our release. We will not server the entire CouchDB at all any more. Instead we will proxy on database basis at `/hoodie/store/api`, that's what hoodie-server-store does
